FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore "Tamplate.Subscriber/Tamplate.Subscriber.csproj"

FROM build AS publish
RUN dotnet publish "Tamplate.Subscriber/Tamplate.Subscriber.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "Tamplate.Subscriber.dll"]
